var _lisapatterns =  {
	exposition:
	[
		/*{
			sequence:['demystify','scopeSideways']
		},
		{
			sequence:['demystify','demystify','scopeSideways']
		},
		{
			sequence:['demystify','demystify','scopeDown']
		},	
		{
			sequence:['demystify','demystify','scopeUp']
		},*/
		{
			sequence:['demystify','express-relationship']
		}	
	],
	service:
	[
		{
			sequence:['greet']
		},
		{
			sequence:['greet','demystify-self']
		},
		{
			sequence:['demystify-self','share-ego']
		},
		{
			sequence:['demystify-self','share-ego','demystify-self']
		},
		{
			sequence:['demystify-self']
		},
	],

	greeting:
	[
		{
			sequence:['greet','share-ego']
		},
		{
			sequence:['greet','share-ego','share-ego']
		},
		{
			sequence:['greet','share-ego','demystify-self']
		},
	]
	}