var _lisapatterns =  {
	exposition:
	[
		/*
		{
			sequence:['demystify','scopeSideways']
		},
		{
			sequence:['demystify','demystify','scopeSideways']
		},
		{
			sequence:['demystify','demystify','scopeDown']
		},	
		{
			sequence:['demystify','demystify','scopeUp']
		},
		*/
		{
			sequence:['demystify','express-relationship']
		},
		{
			sequence:['demystify','tell-story']
		},
	],

	greeting:
	[
		{
			sequence:['greet','share-ego']
		},
		{
			sequence:['greet','share-ego','share-ego']
		},
		{
			sequence:['greet','share-ego','demystify-self']
		},
	]
	}